# Generated by Django 2.1.7 on 2019-03-16 20:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrzerwaWPracyPionu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('koniec', models.DateField()),
                ('przyczyna', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piony.Pion')),
            ],
        ),
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9dab0eea-409e-413b-b0cf-641a37b04545'), editable=False, unique=True),
        ),
    ]
