# Generated by Django 2.1.7 on 2019-03-16 21:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0002_auto_20190316_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c82cc4ef-32a7-4864-9522-534e983db0be'), editable=False, unique=True),
        ),
    ]
