# Generated by Django 2.1.7 on 2019-03-16 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0002_auto_20190316_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='przerwawpracypionu',
            options={'verbose_name': 'przerwa w pracy pionu', 'verbose_name_plural': 'przerwy w pracy pionu'},
        ),
        migrations.AddField(
            model_name='zyczeniapracownika',
            name='maks_dniowki',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Maks. dniówek'),
        ),
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d677124e-bc17-4151-ab89-ca32f25ee3c1'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='przerwawpracypionu',
            name='przyczyna',
            field=models.CharField(default='nie pracuje', max_length=50),
        ),
    ]
