# Generated by Django 2.1.7 on 2019-03-17 09:51

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('piony', '0004_auto_20190317_0024'), ('piony', '0005_auto_20190317_0038'), ('piony', '0006_auto_20190317_1050'), ('piony', '0007_auto_20190317_1050'), ('piony', '0008_auto_20190317_1050')]

    dependencies = [
        ('piony', '0003_auto_20190316_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafik',
            name='parent',
        ),
        migrations.AddField(
            model_name='zyczeniapracownika',
            name='maks_dyzury',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Maks. dyżurów'),
        ),
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8e74cf8c-99e8-40c1-b79a-f6653225b2f2'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3d16f7c3-5d38-4d60-a991-30aaf038957e'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('34839295-248f-4b5d-997c-a569b3f0bf01'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='zyczeniapracownika',
            name='min_odpoczynek_po_ciaglej_pracy',
            field=models.PositiveIntegerField(default=11, validators=[django.core.validators.MaxValueValidator(24)], verbose_name='Czas bez pracy po godzinach ciągłej pracy'),
        ),
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e82d62e5-be42-483c-9889-bffcf555c9b8'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c74790d8-e41d-4307-8661-dd6865772032'), editable=False, unique=True),
        ),
    ]
