# Generated by Django 2.1.7 on 2019-03-16 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0004_auto_20190317_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3d16f7c3-5d38-4d60-a991-30aaf038957e'), editable=False, unique=True),
        ),
    ]
