# Generated by Django 2.1.7 on 2019-03-17 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0005_auto_20190317_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='PionNiePracuje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien', models.DateField(db_index=True)),
                ('przyczyna', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2f1c4faa-297e-43fb-b5ed-9fecf3eb47dd'), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='pionniepracuje',
            name='grafik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piony.Grafik'),
        ),
        migrations.AddField(
            model_name='pionniepracuje',
            name='pion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piony.Pion'),
        ),
    ]
