# Generated by Django 2.1.7 on 2019-03-17 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0006_auto_20190317_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e82d62e5-be42-483c-9889-bffcf555c9b8'), editable=False, unique=True),
        ),
    ]
