# Generated by Django 2.1.7 on 2019-03-17 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0006_auto_20190317_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('12f6a129-8776-4fc5-9da9-7a944eaf1ff6'), editable=False, unique=True),
        ),
    ]
