# Generated by Django 2.1.7 on 2019-03-17 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0007_auto_20190317_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c74790d8-e41d-4307-8661-dd6865772032'), editable=False, unique=True),
        ),
    ]
