# Generated by Django 2.1.7 on 2019-03-17 15:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0007_auto_20190317_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementWydruku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.PositiveSmallIntegerField(choices=[(1, 'Dzień'), (2, 'Dzień tygodnia'), (3, 'Pion')])),
                ('kolejnosc', models.PositiveSmallIntegerField(default=0)),
                ('pion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piony.Pion')),
            ],
        ),
        migrations.CreateModel(
            name='Wydruk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=32, unique=True)),
                ('nazwa', models.CharField(blank=True, max_length=100, null=True)),
                ('rodzaj', models.PositiveSmallIntegerField(choices=[(1, 'miesięczny'), (1, 'tygodniowy')])),
            ],
        ),
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('701663e2-171a-4fc6-a30a-5549dca6056a'), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='elementwydruku',
            name='wydruk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piony.Wydruk'),
        ),
    ]
