# Generated by Django 2.1.7 on 2019-03-17 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0008_auto_20190317_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementwydruku',
            options={'ordering': ['kolejnosc'], 'verbose_name': 'element wydruku', 'verbose_name_plural': 'elementy wydruku'},
        ),
        migrations.AlterModelOptions(
            name='wydruk',
            options={'verbose_name': 'wydruk', 'verbose_name_plural': 'wydruki'},
        ),
        migrations.AddField(
            model_name='pionniepracuje',
            name='zmodyfikowano',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wolne',
            name='zmodyfikowano',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wpis',
            name='zmodyfikowano',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9e38245-c416-405f-a4f2-4fe0c8284f0f'), editable=False, unique=True),
        ),
    ]
