# Generated by Django 2.1.7 on 2019-03-17 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0009_auto_20190317_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafik',
            name='miesiac',
        ),
        migrations.AddField(
            model_name='grafik',
            name='nazwa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grafik',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
