# Generated by Django 2.1.7 on 2019-03-17 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piony', '0010_auto_20190317_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nierozpisany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien', models.DateField(db_index=True)),
                ('zmodyfikowano', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='grafik',
            options={'verbose_name': 'grafik', 'verbose_name_plural': 'grafiki'},
        ),
        migrations.AlterField(
            model_name='elementwydruku',
            name='rodzaj',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dzień'), (2, 'Dzień tygodnia'), (3, 'Pion'), (4, 'Wolne'), (5, 'Nierozpisani')]),
        ),
        migrations.AddField(
            model_name='nierozpisany',
            name='grafik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piony.Grafik'),
        ),
        migrations.AddField(
            model_name='nierozpisany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
