# Generated by Django 2.1.7 on 2019-03-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0011_auto_20190317_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafik',
            name='pion_dla_nierozpisanych',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piony.Pion'),
        ),
    ]
