# Generated by Django 2.1.7 on 2019-03-17 21:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import piony.models.grafik


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0012_grafik_pion_dla_nierozpisanych'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZestawiajRazem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzienny', mptt.fields.TreeForeignKey(limit_choices_to=piony.models.grafik.dzienne, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='piony.Pion')),
                ('nocnyswiateczny', mptt.fields.TreeForeignKey(limit_choices_to=piony.models.grafik.nocneswiateczne, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='piony.Pion')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piony.Grafik')),
            ],
        ),
    ]
