# Generated by Django 2.1.7 on 2019-03-17 21:43

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0013_zestawiajrazem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zestawiajrazem',
            name='dzienny',
            field=mptt.fields.TreeForeignKey(limit_choices_to={'rodzaj': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='piony.Pion'),
        ),
        migrations.AlterField(
            model_name='zestawiajrazem',
            name='nocnyswiateczny',
            field=mptt.fields.TreeForeignKey(limit_choices_to={'rodzaj': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='piony.Pion'),
        ),
    ]
