# Generated by Django 2.1.7 on 2019-03-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0014_auto_20190317_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priorytet',
            options={'ordering': ['kolejnosc'], 'verbose_name': 'priorytet', 'verbose_name_plural': 'priorytety'},
        ),
        migrations.AddField(
            model_name='priorytet',
            name='kolejnosc',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
