# Generated by Django 2.1.7 on 2019-03-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0017_kolejkadopionudump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kolejkadopionudump',
            name='grafik',
        ),
        migrations.RemoveField(
            model_name='kolejkadopionudump',
            name='pion',
        ),
        migrations.AddField(
            model_name='wpis',
            name='kolejkaDump',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='KolejkaDoPionuDump',
        ),
    ]
