# Generated by Django 2.1.7 on 2019-03-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0019_auto_20190318_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydruk',
            name='font_size',
            field=models.CharField(blank=True, help_text='CSS font-size; może być w pt, px, em...', max_length=10, null=True, verbose_name='Wielkość czcionki'),
        ),
    ]
