# Generated by Django 2.1.7 on 2019-03-23 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0020_auto_20190318_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='DostepnoscOgolnaPionu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adnotacja', models.CharField(blank=True, max_length=50, null=True)),
                ('start', models.DateField(blank=True, null=True, verbose_name='Początek')),
                ('koniec', models.DateField(blank=True, null=True, verbose_name='Koniec')),
                ('dzien_1', models.BooleanField(default=True, verbose_name='Pon.')),
                ('dzien_2', models.BooleanField(default=True, verbose_name='Wt.')),
                ('dzien_3', models.BooleanField(default=True, verbose_name='Śr.')),
                ('dzien_4', models.BooleanField(default=True, verbose_name='Czw.')),
                ('dzien_5', models.BooleanField(default=True, verbose_name='Pt.')),
                ('dzien_6', models.BooleanField(default=True, verbose_name='Sob.')),
                ('dzien_7', models.BooleanField(default=True, verbose_name='Nie.')),
                ('dostepny', models.BooleanField(default=True, verbose_name='Dostępny/a')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'dostępność ogólna pionu',
                'verbose_name_plural': 'dostępności ogólne pionów',
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.AddField(
            model_name='pion',
            name='domyslnie_dostepny',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dostepnoscogolnapionu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piony.Pion'),
        ),
    ]
