# Generated by Django 2.2 on 2019-04-09 23:12

from django.db import migrations

from piony import const


def przenies_wolne(apps, schema_editor):
    Wolne = apps.get_model("piony", "Wolne")
    Pion = apps.get_model("piony", "Pion")
    Wpis = apps.get_model("piony", "Wpis")
    Grafik = apps.get_model("piony", "Grafik")

    poza_praca = dict([(p.nazwa, p) for p in Pion.objects.filter(rodzaj=const.POZA_PRACA)])

    for elem in Wolne.objects.all():
        if elem.przyczyna not in poza_praca:
            raise ValueError(elem.przyczyna)

        Wpis.objects.create(
            grafik=elem.grafik,
            dzien=elem.dzien,
            user=elem.user,
            pion=poza_praca[elem.przyczyna]
        )


class Migration(migrations.Migration):
    dependencies = [
        ('piony', '0023_zyczeniaogolne_tylko_dni_powszednie'),
    ]

    operations = [
        migrations.RunPython(przenies_wolne, migrations.RunPython.noop)
    ]
