# Generated by Django 2.2 on 2019-04-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0025_auto_20190410_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='pion',
            name='symbol',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='elementwydruku',
            name='rodzaj',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Data'), (2, 'Dzień tygodnia'), (8, 'Dzień miesiąca'), (3, 'Pion'), (6, 'Pion dzienny'), (7, 'Pion dyżurowy'), (30, 'Pion i podrzędne')]),
        ),
    ]
