# Generated by Django 2.2 on 2019-04-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piony', '0027_auto_20190410_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='pion',
            name='ilosc_godzin',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Jeżeli jest to pion nocny (popołudniowy) np. żylaki od 15tej do 19tej, wpisz tutaj przeciętną ilość godzin dla tego pionu. Jeżeli jest to zwykły, pełny pion dyżurowy lub dzienny (16, 24, 8 godzin) to pozostaw to pole puste. ', null=True),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='template',
            field=models.TextField(blank=True, default='{{user.last_name}} {{user.first_name|first|capfirst}}.', null=True),
        ),
    ]
