DZIENNY = 1
NOCNYSWIATECZNY = 2
POZA_PRACA = 3

REZYDENT = 0
JEDYNKOWICZ = 1
SPECJALISTA = 2

URLOP = 1
SZCZEGOLOWE = 2
OGOLNE = 3
BRAK_PRZYPISANIA = 4
ZGLOSZONY_NIEDOSTEPNY_KONKRETNY_PION = 5
ZGLOSZONY_NIEDOSTEPNY_RODZAJ_PIONU = 6
PRZEKROCZONY_CZAS_CIAGLEJ_PRACY = 7
ZBYT_MALY_ODPOCZYNEK = 8
DNIOWKA_ZA_WCZESNIE = 9
MAKS_DNIOWKI_W_MIESIACU = 10
MAKS_DNIOWKI_W_TYGODNIU = 11
MAKS_DYZURY_W_MIESIACU = 12
MAKS_DYZURY_ZWYKLE_W_MIESIACU = 13
MAKS_DYZURY_DOBOWE_W_MIESIACU = 14
DYZUR_ZA_WCZESNIE = 15
NIE_DYZURUJE_Z = 16
NIEDOPASOWANE = 17
ZYCZENIE = 18

PONAD_24_GODZINY = 25

MIESIECZNY = 1
TYGODNIOWY = 2

KOLUMNA_DATA = 1
KOLUMNA_DZIEN_TYGODNIA = 2
KOLUMNA_PION = 3
KOLUMNA_WOLNE = 4
KOLUMNA_NIEROZPISANI = 5
KOLUMNA_PION_DZIENNY = 6
KOLUMNA_PION_NOCNYSWIATECZNY = 7
KOLUMNA_DZIEN_MIESIACA = 8
